### ISSUE TITLE
Catch and handle InvalidLogin exeption

### ISSUE THREAD

**Issue by vterdunov** [vterdunov/janna#57]
```ruby
2017-11-27T10:21:20.495Z 1 TID-4veud9p4 VMwareDestroyVM JID-53ccd90ae64f6c6bac13106c INFO: start
2017-11-27 10:21:20 DEBUG: Get Virtualized Infrastructure Manager
2017-11-27T10:21:23.986Z 1 TID-4veud9p4 VMwareDestroyVM JID-53ccd90ae64f6c6bac13106c INFO: fail: 3.492 sec
2017-11-27T10:21:23.987Z 1 TID-4veud9p4 WARN: {"context":"Job raised exception","job":{"class":"VMwareDestroyVM","args":[{"host":"CENSORED","port":"443","user":"CENSORED","password":"CENSORED","datacenter":"DC","datastore":"datastore","computer_path":"CP","network":"VMnet","vm_folder":"Janna","template_path":"Templates","path":"/sdk","insecure":true,"ssl":true,"debug":false,"provider_type":"vmware","vmname":"LDX-E-autotests-daily-APP_266","message_to":"#ldxe-devops"}],"retry":false,"queue":"default","jid":"53ccd90ae64f6c6bac13106c","created_at":1511778080.4874258,"enqueued_at":1511778080.4942713},"jobstr":"{\"class\":\"VMwareDestroyVM\",\"args\":[{\"host\":\"CENSORED\",\"port\":\"443\",\"user\":\"CENSORED\",\"password\":\"CENSORED\",\"datacenter\":\"DC\",\"datastore\":\"datastore\",\"computer_path\":\"CP\",\"network\":\"VMnet\",\"vm_folder\":\"Janna\",\"template_path\":\"Templates\",\"path\":\"/sdk\",\"insecure\":true,\"ssl\":true,\"debug\":false,\"provider_type\":\"vmware\",\"vmname\":\"LDX-E-autotests-daily-APP_266\",\"message_to\":\"#ldxe-devops\"}],\"retry\":false,\"queue\":\"default\",\"jid\":\"53ccd90ae64f6c6bac13106c\",\"created_at\":1511778080.4874258,\"enqueued_at\":1511778080.4942713}"}
2017-11-27T10:21:23.987Z 1 TID-4veud9p4 WARN: RbVmomi::Fault: InvalidLogin: Cannot complete login due to an incorrect user name or password.
2017-11-27T10:21:23.987Z 1 TID-4veud9p4 WARN: /usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/connection.rb:63:in `parse_response'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/connection.rb:92:in `call'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/basic_types.rb:213:in `_call'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/basic_types.rb:76:in `block (2 levels) in init'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/vim.rb:61:in `block in connect'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/vim.rb:46:in `tap'
/usr/local/bundle/gems/rbvmomi-1.11.2/lib/rbvmomi/vim.rb:46:in `connect'
/usr/src/lib/services/providers/rbvmomi_wrapper.rb:7:in `vim'
/usr/src/lib/services/providers/rbvmomi_wrapper.rb:37:in `vim'
/usr/src/lib/workers/abstract_worker.rb:18:in `vim'
/usr/src/lib/workers/abstract_worker.rb:12:in `perform'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:199:in `execute_job'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/usr/local/bundle/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:169:in `block in process'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:97:in `local'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:215:in `stats'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/job_logger.rb:7:in `call'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:72:in `global'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:129:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:44:in `with_context'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:128:in `dispatch'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:168:in `process'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:85:in `process_one'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:73:in `run'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:16:in `watchdog'
/usr/local/bundle/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by vterdunov** [comment]
Fixed in 0.8.2
